# Copyright 2023 Palantir Technologies Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0.
openapi: 3.0.1
info:
  description: The public API for Apollo
  title: Palantir API
  version: 1.0.0
components:
  securitySchemes:
    BearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: "/multipass/api/oauth2/token"
          authorizationUrl: "/multipass/api/oauth2/authorize"
          refreshUrl: "/multipass/api/oauth2/token"
          scopes:
            apollo-api:use-api: Use API
        clientCredentials:
          tokenUrl: "/multipass/api/oauth2/token"
          scopes:
            apollo-api:use-api: Use API
  schemas:
    TimeInterval:
      description: A time window, comprised of a start and end time
      properties:
        startTime:
          type: string
          format: date-time
          description: The start time for the interval
        endTime:
          type: string
          format: date-time
          description: The end time for the interval
      type: object
    MaintenanceWindow:
      description: A time period during which maintenance can occur
      properties:
        zoneId:
          type: string
        name:
          description: The name for the maintenance window
          type: string
        timeIntervals:
          items:
            $ref: '#/components/schemas/TimeInterval'
          type: array
      type: object
    PageSize:
      description: The page size to use for the endpoint.
      type: integer
    PageToken:
      description: |
        The page token indicates where to start paging. This should be omitted from the first page's request.
        To fetch the next page, clients should take the value from the `nextPageToken` field of the previous response
        and populate the next request's `pageToken` field with it.
      type: string
    ProductId:
      description: The unique identifier for a Product.
      type: string
    GroupId:
      description: A grouping of products based upon coordinate
      type: string
    PackageRid:
      description: The unique resource identifier for a Package, useful for interacting with other Apollo APIs
      format: rid
      type: string
    ReleaseChannel:
      type: string
    ApolloEntityId:
      description: A deterministic, client creatable, identifier for an Apollo resource
      type: string
    ApolloProductVersion:
      description: An orderable semantically versioned string
      type: string
paths: {}
