# Copyright 2023 Palantir Technologies Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0.
openapi: 3.0.1
info:
  description: The public API for Apollo
  title: Apollo API
  version: 0.1.0
servers:
  - url: /api
tags:
  - name: PingApiService
    x-serviceName: true
components:
  securitySchemes:
    BearerAuth:
      $ref: './common.yml#/components/securitySchemes/BearerAuth'
    OAuth2:
      $ref: './common.yml#/components/securitySchemes/OAuth2'
  schemas: {}
paths:
  /v0/ping:
    get:
      description: |
        Simple ping/pong service that validates that the user is authenticated and is able to make requests
      operationId: ping
      security:
        - OAuth2: [ ]
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: pong
      tags:
        - PingApiService
