# Copyright 2023 Palantir Technologies Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0.
openapi: 3.0.1
info:
  description: The public API for Apollo.
  title: Apollo API
  version: 0.1.0
servers:
  - url: /api
tags:
  - name: ProductsApiService
    x-serviceName: true
components:
  securitySchemes:
    BearerAuth:
      $ref: './common.yml#/components/securitySchemes/BearerAuth'
    OAuth2:
      $ref: './common.yml#/components/securitySchemes/OAuth2'
  schemas:
    ProductVersion:
      type: string
    MavenCoordinate:
      type: string
    UpgradeStrategy:
      type: string
      enum: [rolling, shutdown]
    ProductDependency:
      properties:
        productId:
          $ref: "./common.yml#/components/schemas/ProductId"
        minVersion:
          $ref: "./common.yml#/components/schemas/ApolloProductVersion"
        maxVersion:
          $ref: "./common.yml#/components/schemas/ApolloProductVersion"
        optional:
          type: boolean
      type: object
    RecallStatus:
      description: |
        An object describing the recalled state for a given product release. 
        If recalled is false, other properties will not be filled out.
      properties:
        recalled:
          type: boolean
          description: True if the release is recalled, false otherwise.
        recalledBy:
          type: string
          description: The unique user identifier for the user that initiated the recall.
        recalledAt:
          type: string
          format: date-time
        reason:
          type: string
      type: object
      required:
        - recalled
    HelmChartProductExtensions:
      description: |
        An object describing the helm chart product extensions for a product release.
      properties:
        helmChart:
          $ref: '#/components/schemas/HelmChartReleaseLocator'
        artifacts:
          items:
            $ref: '#/components/schemas/ArtifactLocator'
          type: array
        productDependencies:
          items:
            $ref: '#/components/schemas/ProductDependencyLocator'
          type: array
      type: object
      required:
        - helmChart
    ServiceProductExtensions:
      description: |
        An object describing the service product extensions for a product release.
      properties:
        productDependencies:
          items:
            $ref: '#/components/schemas/ProductDependencyLocator'
          type: array
      type: object
    HelmChartReleaseLocator:
      description: |
        An object describing the helm chart release for a product release.
      properties:
        helmRepositoryUrl:
          type: string
        helmChartName:
          type: string
        helmChartVersion:
          $ref: "./common.yml#/components/schemas/ApolloProductVersion"
      required:
        - helmRepositoryUrl
        - helmChartName
        - helmChartVersion
      type: object
    ArtifactLocator:
      description: |
        An object describing an OCI artifact for a product release.
      properties:
        artifactUrl:
          type: string
          description: An OCI registry URL without the url protocol
      required:
        - artifactUrl
      type: object
    ProductDependencyLocator:
      description: |
        An object describing a product dependency for a product release.
      properties:
        productGroup:
          type: string
          description: Product group for the dependent product release.
        productName:
          type: string
          description: Product name for the dependent product release.
        minimumVersion:
          $ref: "./common.yml#/components/schemas/ApolloProductVersion"
        maximumVersion:
          $ref: "./common.yml#/components/schemas/ApolloProductVersion"
      required:
        - productGroup
        - productName
        - minimumVersion
        - maximumVersion
      type: object
    Release:
      properties:
        mavenCoordinate:
          $ref: '#/components/schemas/MavenCoordinate'
        releaseChannels:
          items:
            $ref: './common.yml#/components/schemas/ReleaseChannel'
          type: array
        upgradeStrategy:
          $ref: '#/components/schemas/UpgradeStrategy'
        recallStatus:
          $ref: '#/components/schemas/RecallStatus'
        productDependencies:
          items:
            $ref: '#/components/schemas/ProductDependency'
          type: array
      required:
        - mavenCoordinate
        - recallStatus
      type: object
    Product:
      description: An Apollo Product.
      properties:
        id:
          $ref: "./common.yml#/components/schemas/ProductId"
        group:
          $ref: "./common.yml#/components/schemas/GroupId"
        maintenanceWindow:
          $ref: './common.yml#/components/schemas/MaintenanceWindow'
        ownerTeamRid:
          $ref: './teams.yml#/components/schemas/TeamRid'
      required:
        - id
        - group
      type: object
    PublishServiceRequest:
      properties:
        extensions:
          description: Product extensions for the service.
          $ref: '#/components/schemas/ServiceProductExtensions'
      type: object
    PublishHelmChartRequest:
      properties:
        extensions:
          description: Product extensions for the helm chart.
          $ref: '#/components/schemas/HelmChartProductExtensions'
      required:
        - extensions
      type: object
    PublishServiceResponse:
      type: object
    PublishHelmChartResponse:
      type: object
    ListProductsResponse:
      properties:
        products:
          description: The list of Products the user has access to.
          items:
            $ref: '#/components/schemas/Product'
          type: array
      type: object
    ListReleasesResponse:
      properties:
        releases:
          description: The list of Releases for a specific Product.
          items:
            $ref: '#/components/schemas/Release'
          type: array
      type: object
paths:
  /v0/products/helmChart/{mavenCoordinate}/publish:
    post:
      description: Publishes an Apollo helm chart manifest.
      operationId: publishHelmChart
      security:
        - OAuth2: []
        - BearerAuth: []
      parameters:
        - description: The maven coordinate specified for the product release.
          in: path
          name: mavenCoordinate
          required: true
          schema:
            $ref: '#/components/schemas/MavenCoordinate'
          example: com.apollo.autodiscovery:wordpress:12.1.3
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishHelmChartRequest'
            example:
              extensions:
                helmChart:
                  helmChartName: wordpress
                  helmChartVersion: 12.1.3
                  helmRepositoryUrl: https://charts.bitnami.com/charts
                artifacts:
                  - artifactUrl: docker.io/wordpress:12.1.3
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishHelmChartResponse'
              example: {}
          description: Success response.
      tags:
        - ProductsApiService
  /v0/products/service/{mavenCoordinate}/publish:
    post:
      description: Publishes an Apollo service manifest.
      operationId: publishService
      security:
        - OAuth2: []
        - BearerAuth: []
      parameters:
        - description: The maven coordinate specified for the product release.
          in: path
          name: mavenCoordinate
          required: true
          schema:
            $ref: '#/components/schemas/MavenCoordinate'
          example: com.apollo.autodiscovery:wordpress:12.1.3
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishServiceRequest'
            example:
              extensions:
                productDependencies:
                  - productGroup: com.apollo.autodiscovery
                    productName: mariadb
                    minimumVersion: 0.1.0
                    maximumVersion: 0.3.0
                    optional: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishServiceResponse'
              example: {}
          description: Success response.
      tags:
        - ProductsApiService
  /v0/products:
    get:
      description: Lists products the user has access to.
      operationId: listProducts
      security:
        - OAuth2: [ ]
        - BearerAuth: [ ]
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListProductsResponse'
          description: Success response
      tags:
        - ProductsApiService
  /v0/products/{productId}:
    get:
      description: Fetches the product specified by the provided ProductID.
      operationId: getProduct
      security:
        - OAuth2: [ ]
        - BearerAuth: [ ]
      parameters:
        - description: The ProductID of the Product.
          in: path
          name: productId
          required: true
          schema:
            $ref: "./common.yml#/components/schemas/ProductId"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: Success response.
      tags:
        - ProductsApiService
  /v0/products/{productId}/releases:
    get:
      description: Lists releases for the Product specified by the provided ProductID.
      operationId: listReleases
      security:
        - OAuth2: [ ]
        - BearerAuth: [ ]
      parameters:
        - description: The ProductID of the Product
          in: path
          name: productId
          required: true
          schema:
            $ref: "./common.yml#/components/schemas/ProductId"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListReleasesResponse'
          description: Success response.
      tags:
        - ProductsApiService
  /v0/products/{productId}/releases/{productVersion}:
    get:
      description: Fetches the release for the specified ProductID and Maven Coordinate.
      operationId: getRelease
      security:
        - OAuth2: [ ]
        - BearerAuth: [ ]
      parameters:
        - description: The ProductID of the Product
          in: path
          name: productId
          required: true
          schema:
            $ref: "./common.yml#/components/schemas/ProductId"
        - description: The version number for the Release.
          in: path
          name: productVersion
          required: true
          schema:
            $ref: "#/components/schemas/ProductVersion"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Release'
          description: Success response.
      tags:
        - ProductsApiService
